---

server:
  hosts:
    node:
      ansible_host:               "{{ lookup('env', 'SSH_HOST') }}"
      ansible_port:               "{{ lookup('env', 'SSH_PORT') }}"
      ansible_user:               "{{ lookup('env', 'SSH_USER') }}"
      ansible_python_interpreter: /usr/bin/python2